name: Go Test

on: 
  push:

  issues:
    types:
      - opened
  schedule:
    - cron: '10 9 * * *'
  label:
    types:
      - created


jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'development')
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v .
