name: Manual Release and Deploy

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'Release branch name'
        required: true
        default: 'release/'

  issue_comment:
    types: [created]

jobs:
  create-release-branch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release Branch
        run: git checkout -b ${{ github.event.inputs.releaseBranch }} && git push origin ${{ github.event.inputs.releaseBranch }}

  deploy:
    if: >
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, 'OK') &&
      github.event.issue.pull_request
    runs-on: ubuntu-latest
    needs: create-release-branch
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to production..."
        # 배포 스크립트를 여기에 추가하세요.